#!/usr/bin/env python
# -*- encoding:utf-8 -*-
from django.utils.translation import ugettext_lazy as _

NETWORK_STATE_BUILD = 0
NETWORK_STATE_ACTIVE = 1
NETWORK_STATE_DOWN = 2
NETWORK_STATE_ERROR = 3
NETWORK_STATE_CREATING = 4
NETWORK_STATE_DELETING = 5
NETWORK_STATE_UPDATING = 6


NETWORK_STATES = (
    (NETWORK_STATE_BUILD, _("BUILD")), #0
    (NETWORK_STATE_ACTIVE, _("ACTIVE")), #1
    (NETWORK_STATE_DOWN, _("DOWN")), #2
    (NETWORK_STATE_ERROR, _("ERROR")),#3
    (NETWORK_STATE_CREATING, _("CREATING")),#4
    (NETWORK_STATE_DELETING, _("DELETING")),#5
    (NETWORK_STATE_UPDATING, _("UPDATING")),#6
)


#network 的状态描述字典,  其中包含描述信息和该状态是否稳定的标识信息
#0表示不稳定，1表示稳定
NETWORK_STATES_DICT = {
    NETWORK_STATE_BUILD: (_("BUILD"), 0),
    NETWORK_STATE_ACTIVE: (_("ACTIVE"), 1),
    NETWORK_STATE_DOWN: (_("DOWN"), 1),
    NETWORK_STATE_ERROR: (_("ERROR"), 1),
    NETWORK_STATE_CREATING: (_("CREATING"), 0),
    NETWORK_STATE_DELETING: (_("DELETING"), 0),
    NETWORK_STATE_UPDATING: (_("UPDATING"), 0),
}
